/*
 * generated by Xtext 2.10.0
 */
package com.rainerschuster.jdl.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class JdlDslUiModule extends AbstractJdlDslUiModule {
}
