/*
 * generated by Xtext 2.10.0
 */
package com.rainerschuster.jdl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class JdlDslStandaloneSetup extends JdlDslStandaloneSetupGenerated {

	def static void doSetup() {
		new JdlDslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
