/*
 * generated by Xtext 2.10.0
 */
package com.rainerschuster.jdl.idea

import org.eclipse.xtext.ISetup
import org.eclipse.xtext.idea.extensions.EcoreGlobalRegistries

class JdlDslIdeaSetup implements ISetup {

	override createInjectorAndDoEMFRegistration() {
		EcoreGlobalRegistries.ensureInitialized
		new JdlDslStandaloneSetupIdea().createInjector
	}

}
