/*
 * generated by Xtext 2.10.0
 */
package com.rainerschuster.jdl.idea


/**
 * Use this class to register components to be used within IntelliJ IDEA.
 */
class JdlIdeaModule extends AbstractJdlIdeaModule {
}
