/*
 * generated by Xtext 2.10.0
 */
package com.rainerschuster.jdl.idea.lang


class JdlDslFileType extends AbstractJdlDslFileType {
	public static final JdlDslFileType INSTANCE = new JdlDslFileType()
	
	new() {
		super(JdlDslLanguage.INSTANCE)
	}
}
