/*
 * generated by Xtext 2.10.0
 */
package com.rainerschuster.jdl.idea.lang


class JdlFileType extends AbstractJdlFileType {
	public static final JdlFileType INSTANCE = new JdlFileType()
	
	new() {
		super(JdlLanguage.INSTANCE)
	}
}
