/*
 * generated by Xtext 2.10.0
 */
package com.rainerschuster.jdl.idea.completion

import com.rainerschuster.jdl.idea.lang.JdlLanguage
import org.eclipse.xtext.idea.lang.AbstractXtextLanguage

class JdlCompletionContributor extends AbstractJdlCompletionContributor {
	new() {
		this(JdlLanguage.INSTANCE)
	}
	
	new(AbstractXtextLanguage lang) {
		super(lang)
		//custom rules here
	}
}
