/*
 * generated by Xtext 2.10.0
 */
package com.rainerschuster.jdl.idea.completion

import com.rainerschuster.jdl.idea.lang.JdlDslLanguage
import org.eclipse.xtext.idea.lang.AbstractXtextLanguage

class JdlDslCompletionContributor extends AbstractJdlDslCompletionContributor {
	new() {
		this(JdlDslLanguage.INSTANCE)
	}
	
	new(AbstractXtextLanguage lang) {
		super(lang)
		//custom rules here
	}
}
